bugfix - 228 - add setReleaseMode method for manage player state
SimformSolutionsPvtLtd/audio_waveforms pull request #269
Opened 2024-02-20 13:42 UTC by himanshuGandhiSimform

BugFix - 228 - Add setRelease Mode as per the requirement

2024-02-20 17:09 UTC, ujas-m-simformsolutions requested changes
Some files look unformatted in native android and ios. Please format those

2024-02-20 17:09 UTC, ujas-m-simformsolutions commented on lib/src/base/utils.dart
> +enum ReleaseMode{
Let's not change the name of the enum because then it will be a bigger breaking change

2024-02-20 17:09 UTC, ujas-m-simformsolutions commented on android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
> +                when (releaseModeType) {
This looks much better than previous

2024-02-22 07:21 UTC, himanshuGandhiSimform commented on android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
> +                when (releaseModeType) {
Thank you Mmmmm…

2024-03-14 14:13 UTC, ujas-m-simformsolutions commented on lib/src/base/utils.dart
> +  /// let it go. Data will be buffered again when needed (if it's a remote file,
We don't support remote files so remove it.

2024-03-14 14:13 UTC, ujas-m-simformsolutions commented on lib/src/base/utils.dart
> +  /// let it go. Data will be buffered again when needed (if it's a remote file,
Or even better can replace this whole docs with ours

2024-03-14 14:14 UTC, ujas-m-simformsolutions commented on lib/src/controllers/player_controller.dart
> +  Future<void> setReleaseMode(FinishMode  finishMode)async{
Make named parameter with default value and format

2024-10-18 14:02 UTC, ujas-m-simformsolutions requested changes

2024-10-18 14:02 UTC, ujas-m-simformsolutions commented on android/src/main/kotlin/com/simform/audio_waveforms/Utils.kt
> +}
I guess this was mistakenly added.

2024-10-18 14:02 UTC, ujas-m-simformsolutions commented on android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt
> +                    }
We now prefer throwing error when there is unknown mode so,
0 -> stop
1-> loop
2 -> pause
else -> error

2024-11-26 08:47 UTC, himanshuGandhiSimform commented on lib/src/base/utils.dart
> -  stop
this is same as release mode that's why

2024-12-02 08:16 UTC, ujas-m-simformsolutions approved these changes

2024-12-02 08:16 UTC, merged

2024-12-11 05:55 UTC, lhengl commented
This merge is a breaking change due to the removal of finishMode as a parameter. Some packages that rely on this parameter now breaks (e.g. [chatview](https://pub.dev/packages/chatview)). I suggest to add this back and call setFinishMode as a hotfix. This should be flagged with @deprecated instead so that it can be removed in the next major release. Most packages will not expect a breaking change without bumping the major version.