Upgrade the flutter version
SimformSolutionsPvtLtd/audio_waveforms pull request #278
Opened 2024-03-08 06:12 UTC by himanshuGandhiSimform

Upgrade the flutter version

2024-03-08 06:57 UTC, ujas-m-simformsolutions requested changes
Can you please also update pubspec in example and remove ambigute function since it is unnecessary now? 

Also, please do check after upgrading if we have to any key in info.plist or have to update gradle file.

2024-03-12 15:27 UTC, Ujas-Majithiya commented on android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
> +        if (frequency == 50) {
we can directly use value and remove this function as well as the enum

2024-03-12 15:28 UTC, Ujas-Majithiya commented on ios/Classes/SwiftAudioWaveformsPlugin.swift
> +        if(freq == 50){
^^

2024-03-14 13:37 UTC, ujas-m-simformsolutions approved these changes

2024-03-14 13:38 UTC, merged