Added bitrate selection
SimformSolutionsPvtLtd/audio_waveforms pull request #84
Opened 2022-08-19 08:36 UTC by abhay-s-rawat

Added bitrate functionality.
old request is below, please discard old one as it has some changes related to flutter 3 but new one has only changes related to bitrate functionality.
https://github.com/SimformSolutionsPvtLtd/audio_waveforms/pull/53

2022-08-19 16:55 UTC, ujas-m-simformsolutions requested changes

2022-08-19 16:55 UTC, ujas-m-simformsolutions commented on CHANGELOG.md
> +* Added bitRate feature for IOS (Default to 32kbps) (Not Tested).
Combine these changes into just one line and remove `Not Tested`.

2022-08-19 16:55 UTC, ujas-m-simformsolutions commented on android/src/main/kotlin/com/simform/audio_waveforms/AudioWaveformsPlugin.kt
> +    private var bitRate: Int = 32768
I think 32 kbps is too low quality, we should default to 128 kbps.

2022-08-19 16:55 UTC, ujas-m-simformsolutions commented on example/lib/main.dart
> +        print("Recorded file size: ${File(path).lengthSync()}");
use `debugPrint` here.

2022-08-19 16:55 UTC, ujas-m-simformsolutions commented on ios/Classes/AudioRecorder.swift
> +            AVEncoderBitRateKey: bitRate ?? 32768,
Same for ios, make it 128 kbps.

2022-08-20 06:34 UTC, abhay-s-rawat commented
Will do the changes. You will find this funny but previously the bitrate was near 8kbps which is default. lol.
Are you sure bumping it to 128kbps will not have impact on already using users of this package , because after doing above changes the recorded file will be 16 times greater in size than before ?

2022-08-20 07:20 UTC, abhay-s-rawat commented
128kbps is music level quality which user does not want in normal audios. That's why did 32kbps. Do you want me to proceed with 128kbps default ?

2022-08-20 11:25 UTC, ujas-m-simformsolutions commented
@abhay-s-rawat Can you please share how you got the 8 kbps default value?

2022-08-20 11:27 UTC, ujas-m-simformsolutions commented
And now I think, we should just let the platform decide if bitrate is not provided so lets make it `nullable` so if not provided then we won't set anything.

2022-08-20 14:11 UTC, abhay-s-rawat commented
Letting the platform decide will only make things not right, because different platforms have different defaults, it will affect cross platform apps that currently are using this package.
Actually I caculated the audio file size and length and got somewhere near 8kbps so I got that values. I am not aware of platform defaults actually.
I suggest not keeping it too low and not too high. 32kbps/64kbs/96kbps will be best fit. What do you suggest ?

2022-08-24 13:04 UTC, ujas-m-simformsolutions commented
@abhay-s-rawat We can go with the 64 kbps

2022-09-04 09:53 UTC, abhay-s-rawat commented
Sure will do it, sorry for the delay , was but busy somewhere else . Will do changes asap.Thanks for your time

2022-09-07 05:05 UTC, abhay-s-rawat commented
Did above changes as discussed. Sorry for the delay .

2022-09-08 06:07 UTC, merged

2022-09-08 06:08 UTC, ujas-m-simformsolutions commented
@abhay-s-rawat Thank you for your contribution. This will be available in the next release.